services:
  config-server:
    image: "config-server:1.0.0"
    container_name: "config-server"
    ports:
      - "8888:8888"
      - "8000:8001"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
  catalog-service:
    depends_on:
      - polar-catalog-service-postgres
      - config-server
    image: "catalog-service:1.0.0"
    container_name: "catalog-service"
    ports:
      - "9001:9001"
      - "8001:8001"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-catalog-service-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testdata
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
  order-service:
    depends_on:
      - polar-order-service-postgres
    image: "order-service:1.0.0"
    container_name: "order-service"
    ports:
      - "9002:9002"
      - "8002:8001"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_R2DBC_URL=r2dbc:postgresql://polar-order-service-postgres:5432/polardb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://polar-order-service-postgres:5432/polardb_order
  polar-catalog-service-postgres:
    image: "postgres:16"
    container_name: "polar-catalog-service-postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=polardb_catalog
  polar-order-service-postgres:
    image: "postgres:16"
    container_name: "polar-order-service-postgres"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=polardb_order
  polar-redis:
    image: "redis:7.0"
    container_name: "polar-redis"
    ports:
      - "6379:6379"
  polar-rabbitmq:
    image: rabbitmq:3.10-management
    container_name: polar-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
  polar-keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: "polar-keycloak"
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - "8080:8080"

  grafana:
    image: grafana/grafana:9.1.2
    container_name: grafana
    depends_on:
      - loki
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./observability/grafana/datasources/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./observability/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./observability/grafana/grafana.ini:/etc/grafana/grafana.ini
  loki:
    image: grafana/loki:2.6.1
    container_name: loki
    depends_on:
      - fluent-bit
    ports:
      - "3100:3100"
  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:3.1.2-arm64
    container_name: fluent-bit
    ports:
      - "24224:24224"
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./observability/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
  prometheus:
    image: prom/prometheus:v2.38.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml