name: Commit Stage
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Code vulnerability scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "${{ github.workspace }}"
          fail-build: false
          severity-cutoff: 'high'
          acs-report-enable: true

      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

      - name: Build, unit tests and integration tests
        run: |
          chmod +x mvnw
          ./mvnw clean install

      - name: Static code analysis with PMD
        run: |
          chmod +x mvnw
          ./mvnw pmd:check

      - name: Code coverage check with JaCoCo
        run: |
          chmod +x mvnw
          ./mvnw jacoco:check

      - name: OWASP Dependency Check
        run: |
          chmod +x mvnw
          ./mvnw org.owasp:dependency-check-maven:check -Dnvd.apikey=${{ secrets.NVD_API_KEY }}
